### ISSUE TITLE
Extension names are all invalid

### ISSUE THREAD

**Issue by jrtc27** [riscv/riscv-cheri#15]
All extension names in the spec are Zcheri_foo, but extensions can't have _ in them, because it's the separator character.

**Comment by tariqkurd-repo** [comment]
Hi Jessica - glad you're back. All the extension names are also invalid because Zc* relates to 16-bit encodings.
We assigned temporary names so that the intent was clear and will change them when the ARC advise correct ones.
There's no point in trying to come up with "official" ones as they will be changed - this is my Zc experience.

**Comment by jrtc27** [comment]
Sure, the semantic meaning suffers from that, but it's probably best to not pick something as a placeholder that's so blatantly invalid? Or at least add a note if that's intentional?

**Comment by andresag01** [comment]
Hi @jrtc27, you are correct: the names are invalid. Not a lot of thought has gone into this because, as @tariqkurd-repo mentioned, it would be good to have ARC advise. We expect the names to change, so most instances of that in the adoc are actually variables that are very easy to change (see [here](https://github.com/riscv/riscv-cheri/blob/main/src/riscv-cheri.adoc?plain=1#L44)).

**Comment by tariqkurd-repo** [comment]
That text was in there but looks like it didn't make the final version.

**Comment by arichardson** [comment]
> Hi @jrtc27, you are correct: the names are invalid. Not a lot of thought has gone into this because, as @tariqkurd-repo mentioned, it would be good to have ARC advise. We expect the names to change, so most instances of that in the adoc are actually variables that are very easy to change (see [here](https://github.com/riscv/riscv-cheri/blob/main/src/riscv-cheri.adoc?plain=1#L44)).

I agree that using invalid names is not great even if they are placeholders. Maybe just drop the _ for now?

Using the variable is great and will make it easier to change, but I noticed that the usage in headings will still need to be modified since asciidoc does not appear to substitute it there.
