### ISSUE TITLE
behaviour of RV64 M bit with X=0

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-cheri#164]
Currently we have this text:

>For RV64, the M bit can be set to 1 when the capability does not grant <<x_perm>>.
In this case, the M bit is superfluous, so the encoding may be used to support additional features in future extensions

I wonder if we should define that if X is zero, then M must also be zero for the tag to be set.
We could specify that ACPERM will always clear M if it is clearing X. The same is true for ASR - it is superfluous / don't care if X=0.

I think that we shouldn't allow a tagged cap with X=0 and either M=1 or ASR=1, to cleanly reserve these cases for future expansion, and so we should update the ACPERM specification to reflect this.

**Comment by arichardson** [comment]
As you mentioned, I think we can just ignore it in the same way as other "dependent permission bits" for RV64 (ASR without X). The argument for clearing the bit is that it would make RV64 behaviour a bit more similar to RV32 but I don't really know whether that is worthwhile.

Maybe we should re-encode permissions for RV64 as well, but I think keeping them orthogonal is fine since there is little need to save as many bits as there is for RV32.
