### ISSUE TITLE
Remove XLENMAX

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-cheri#67]
The ARC is [considering to make MXLEN constant](https://lists.riscv.org/g/tech-unprivileged/message/646).  If this happens, XLENMAX will become equal to MXLEN in all cases and we can simplify our spec by removing the Zcheri-specific term.

**Comment by andresag01** [comment]
Agreed. It would be good to remove XLENMAX if the ARC accept that proposal.

**Comment by arichardson** [comment]
[2.7.1 already states that MXLEN must be read-only ](https://riscv.github.io/riscv-cheri/#_machine_isa_register_misa)for Zcheri implementations, so maybe we can already drop XLENMAX?

**Comment by andresag01** [comment]
> [2.7.1 already states that MXLEN must be read-only ](https://riscv.github.io/riscv-cheri/#_machine_isa_register_misa) for Zcheri implementations, so maybe we can already drop XLENMAX?

In the current spec, this is only the case for the Zcheri_purecap extension. Zcheri_legacy extension allows configuring MXLEN, SXLEN and UXLEN to any value as long as MXLEN >= SXLEN >= UXLEN in order to "maximize" compatibility with Standard RISC-V which supports that feature (see [here](https://riscv.github.io/riscv-cheri/#_machine_status_registers_mstatus_and_mstatush)), so XLENMAX != MXLEN in some cases.

**Comment by tariqkurd-repo** [comment]
We've discussed this internally - the concern is that on ARC review that they will require writeable MXLEN. If they don't then we are very happy to remove it and have MXLEN==XLENMAX and remove all references to XLENMAX.
