### ISSUE TITLE
Accessing CSRs without ASR permission

### ISSUE THREAD

**Issue by francislaus** [riscv/riscv-cheri#93]
The current form of the spec says that "All non-user mode accessible CSRs require ASR-permission, including existing RISC-V CSRs." We were wondering whether that should hold for all non-user mode accessible CSRs. For example, we think that the `cycle` CSR should be readable on all privilege levels regardless of the ASR-permission.

**Comment by francislaus** [comment]
This is the list of CSRs our cores allow to read:

`FFLAGS`
`FRM`
`FCSR`
`CYCLE`
`TIME`
`INSTRET`

**Comment by arichardson** [comment]
Should this be extended to all performance counter CSRs? S-mode can still disable access for U-mode using `scounteren`? Requiring ASR here seems a bit restrictive. Alternatively, if we are really worried about using them for timing side-channels in compartmentalized programs, there could be a CSR bit that defines whether HPM access needs ASR.

**Comment by andresag01** [comment]
@francislaus : Thanks for pointing this out. The intention is that all registers that are unprivileged according to the RISC-V privileged ISA remain accessible regardless of the ASR permission. This is the list I am talking about from the RISC-V spec (see attachement).
![Screenshot from 2024-02-07 11-06-01](https://github.com/riscv/riscv-cheri/assets/3746901/a29c3e0e-1597-44a7-9b4d-823b449dc66d)

Ideally the CHERI spec uses the same language that the RISC-V privileged spec does, so perhaps it is best to modify this sentence to say _privileged CSRs_ instead of _non-user mode accessible CSRs_.

Does that make sense? Would you like to create a PR to address this wording issue?

**Comment by arichardson** [comment]
I think it would be good to align the ASR behaviour with Table 2.2 in the RISC-V spec. The current sail-cheri-riscv model does not confirm to that behaviour, hopefully the new version for this spec will have it?

**Comment by francislaus** [comment]
I think this raises the question on whether all CSRs are of the same privilege level. For example, reading a counter register does not provide you with the same privilege as being able to write to `mepc`. Code running in M mode that only wants to have access to counters would need the ASR bit set and thus would have more privileges than it should have.

**Comment by tariqkurd-repo** [comment]
@francislaus are you suggesting that ASR should become more than one permission? M-ASR for M-mode state e.g. `mepc`, and S-ASR for S-mode state?

**Comment by jrtc27** [comment]
I'd say no, with the usual "that breaks virtualisation" argument.
