### ISSUE TITLE
Canonical tag clearing pseudo

### ISSUE THREAD

**Issue by arichardson** [riscv/riscv-cheri#94]
ISAv9 had a dedicated CClearTag instruction that writes back the input register without a tag. This is not hugely common. One place I've seen it is in the CheriBSD kernel does for a tag-stripping memcpy since it predates tag-clearing semantics for loads without permit_load_cap.

With #82 we could treat `cbuildcap cd, c0, cs2` as the canonical `ccleartag cd, cs1` (previously I believe the best we could do was the two-instruction `cgethigh cd, cs1; csethigh cd, cs1, cd;`.

1) Should we add a note to buildcap that it might be a good idea for a high-performance CHERI core to special-case `cbuildcap cd, c0, cs2` in the decoder to be a tag-clearing move?

2) Should there be an assembly pseudo for ccleartag that maps to `cbuildcap cd, c0, cs2`?

**Comment by andresag01** [comment]
I like the idea of making `cbuildcap cd, c0, cs2` an assembly pseudo for `ccleartag`. The function is already there and this encoding is probably never going to get used as a hint or something like that.

I am less keen about the informative note because this `ccleartag` is hardly ever used, so I doubt optimising that special cbuildcap case as a move will make any difference for performance.

**Comment by andresag01** [comment]
@francislaus pointed out that `cbuildcap cd, c0, cs2` does not behave like `ccleartag` when otypes are implemented. Given that otypes might be an extension in future, it would be best to add a note to the spec reserving `cbuildcap cd, c0, cs2` instead of declaring it a `ccleartag` pseudo.

**Comment by andresag01** [comment]
Closed via #103
